In [1]:
import sys
import os
from pathlib import Path

In [2]:
def find_project_root(start: Path, anchor_dirs=("src", "Data")) -> Path:
    """
    Walk up the directory tree until we find a folder that
    contains all anchor_dirs (e.g. 'src' and 'Data').
    """
    path = start.resolve()
    for parent in [path] + list(path.parents):
        if all((parent / d).is_dir() for d in anchor_dirs):
            return parent
    raise FileNotFoundError("Could not locate project root")

In [3]:
# Locate the project root regardless of notebook depth
project_root = find_project_root(Path.cwd())

# ----- Code modules --------------------------------------------------
src_path = project_root / "src" / "top20_likelihood"
if str(src_path) not in sys.path:
    sys.path.append(str(src_path))

In [4]:
# Add the src directory to sys.path
src_path = os.path.abspath(os.path.join(os.getcwd(), '..', 'src'))
if src_path not in sys.path:
    sys.path.append(src_path)

In [5]:
from data_prep import preprocess_tdf_data

In [6]:
# ----- Data ----------------------------------------------------------
raw_data_path = project_root / "Data" / "Raw" / "2025"
processed_data_path = project_root / "Data" / "Processed" / "2025"
print("Raw data folder:", raw_data_path)
print("Processed data folder:", processed_data_path)

Raw data folder: C:\Users\Shaun Ricketts\Documents\Projects\Cycling\Tour de France Predictor - 2025\Data\Raw\2025
Processed data folder: C:\Users\Shaun Ricketts\Documents\Projects\Cycling\Tour de France Predictor - 2025\Data\Processed\2025

In [7]:
def run_tdf_preprocessing():
    output_filename = "tdf_prepared_2011_2025.csv"
    output_full_path = os.path.join(processed_data_path, output_filename)

    df = preprocess_tdf_data(raw_data_path, output_full_path)
    print(f"Data preprocessing complete. Output saved to:\n{output_full_path}")
    return df

In [8]:
df = run_tdf_preprocessing()

Wrote prepared data to C:\Users\Shaun Ricketts\Documents\Projects\Cycling\Tour de France Predictor - 2025\Data\Processed\2025\tdf_prepared_2011_2025.csv
Data preprocessing complete. Output saved to:
C:\Users\Shaun Ricketts\Documents\Projects\Cycling\Tour de France Predictor - 2025\Data\Processed\2025\tdf_prepared_2011_2025.csv

In [9]:
df

,Rider_ID,Year,Age,TDF_Pos,Best_Pos_BT_UWT,Best_Pos_BT_PT,Best_Pos_AT_UWT_YB,Best_Pos_AT_PT_YB,Best_Pos_UWT_YB,Best_Pos_PT_YB,...,gt_debut,rode_giro,FC_Points,FC_Pos,Best_Pos_AT_UWT,Best_Pos_AT_PT,Best_Pos_UWT,Best_Pos_PT,Best_Pos_BT_UWT_YB,Best_Pos_BT_PT_YB
0,2,2011,40,NaN,67.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,507,NaN,NaN,67.0,NaN,NaN,NaN
1,3,2011,29,5.0,1.0,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,2685.0,2,NaN,NaN,1.0,NaN,NaN,NaN
2,3,2012,30,NaN,NaN,NaN,NaN,NaN,1.0,NaN,...,NaN,NaN,1719.0,12,1.0,NaN,1.0,NaN,1.0,NaN
3,3,2013,31,4.0,3.0,2.0,1.0,NaN,1.0,NaN,...,NaN,0.0,1622.0,13,NaN,NaN,3.0,2.0,NaN,NaN
4,3,2014,32,DNF,1.0,NaN,NaN,NaN,3.0,2.0,...,NaN,0.0,2893.0,2,1.0,NaN,1.0,NaN,3.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22597,237424,2025,24,NaN,NaN,140.0,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,1,NaN,NaN,NaN,140.0,NaN,NaN
22598,237784,2024,19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,519,NaN,999.0,NaN,999.0,NaN,NaN
22599,237785,2025,21,NaN,NaN,DNF,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,1,NaN,NaN,NaN,999.0,NaN,NaN
22600,240430,2025,25,NaN,NaN,DNF,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,1,NaN,NaN,NaN,999.0,NaN,NaN
22601,246546,2025,24,NaN,NaN,DNF,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,1,NaN,NaN,NaN,999.0,NaN,NaN

In [12]:
df[df["Year"]==2025]

,Rider_ID,Year,Age,TDF_Pos,Best_Pos_BT_UWT,Best_Pos_BT_PT,Best_Pos_AT_UWT_YB,Best_Pos_AT_PT_YB,Best_Pos_UWT_YB,Best_Pos_PT_YB,...,gt_debut,rode_giro,FC_Points,FC_Pos,Best_Pos_AT_UWT,Best_Pos_AT_PT,Best_Pos_UWT,Best_Pos_PT,Best_Pos_BT_UWT_YB,Best_Pos_BT_PT_YB
621,114,2025,39,NaN,81.0,20.0,DNF,42.0,38.0,42.0,...,NaN,NaN,0.0,1,NaN,NaN,81.0,20.0,38.0,999.0
878,163,2025,41,NaN,NaN,68.0,NaN,NaN,DNF,65.0,...,NaN,NaN,0.0,1,NaN,NaN,NaN,68.0,999.0,65.0
1189,264,2025,40,NaN,81.0,40.0,21.0,NaN,21.0,NaN,...,NaN,NaN,0.0,1,NaN,NaN,81.0,40.0,24.0,NaN
1217,277,2025,49,NaN,NaN,10.0,NaN,17.0,NaN,17.0,...,NaN,NaN,0.0,1,NaN,NaN,NaN,10.0,NaN,NaN
1855,406,2025,38,NaN,DNF,48.0,NaN,49.0,99.0,39.0,...,NaN,NaN,0.0,1,NaN,NaN,999.0,48.0,99.0,39.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22596,235082,2025,23,NaN,NaN,35.0,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,1,NaN,NaN,NaN,35.0,NaN,NaN
22597,237424,2025,24,NaN,NaN,140.0,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,1,NaN,NaN,NaN,140.0,NaN,NaN
22599,237785,2025,21,NaN,NaN,DNF,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,1,NaN,NaN,NaN,999.0,NaN,NaN
22600,240430,2025,25,NaN,NaN,DNF,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,1,NaN,NaN,NaN,999.0,NaN,NaN
22601,246546,2025,24,NaN,NaN,DNF,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,1,NaN,NaN,NaN,999.0,NaN,NaN